### ISSUE TITLE
blade加上@uploader(['name' => 'avatar', 'max' => 3, 'accept' => 'jpg,png,gif'])报错

### ISSUE THREAD

**Issue by foridom** [wh469012917/laravel-uploader#6]
Parse error: syntax error, unexpected 'name' (T_STRING), expecting ',' or ')' (View: /home/vagrant/Code/ip-mall/resources/views/welcome.blade.php)

<img width="656" alt="WechatIMG96" src="https://user-images.githubusercontent.com/56290870/76721634-9e23b500-677b-11ea-8dbb-bbe9f446a899.png">

**Comment by wh469012917** [comment]
这个库目前不维护了，设计思路不对
